<?php 
define("APPID","WeChatAppid");
define("TOKEN","WeChatToken");
define("SECRET","WeChatSecret");
define("HOSTNAME","localhost");
define("DB_USERNAME","game_user");
define("DB_PASSWORD","123456");
define("DB_NAME","game");
define("LANGUAGE","zh_CN");
?>